echo 'Train: NB - Unigram - TFIDF - EXCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier 	-t train.arff 	-d train_NB111.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter 		-F \"weka.filters.unsupervised.attribute.StringToWordVector 	-R first-last -W 100000 -prune-rate -1.0 -T -I -N 0 -L 	-S -stemmer weka.core.stemmers.SnowballStemmer -M 1 	-stopwords \\\"E:\\\\\\\\Higher Studies\\\\\\\\STUDY\\\\\\\\Semester3\\\\\\\\NLP\\\\\\\\Project\\\\\\\\MODEL_GEN\\\\\\\\stopwords.txt\\\" 		-tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 1 -min 1\\\"\" 	-F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" 	-W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Unigram - TFIDF - INCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier 	-t train.arff 	-d train_NB112.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter 		-F \"weka.filters.unsupervised.attribute.StringToWordVector 	-R first-last -W 100000 -prune-rate -1.0 -T -I -N 0 -L 	-stemmer weka.core.stemmers.SnowballStemmer -M 1 	-tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 1 -min 1\\\"\" 	-F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" 	-W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Bigram - TFIDF - EXCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB211.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -T -I -N 0 -L -S -stemmer weka.core.stemmers.SnowballStemmer -M 1 -stopwords \\\"E:\\\\\\\\Higher Studies\\\\\\\\STUDY\\\\\\\\Semester3\\\\\\\\NLP\\\\\\\\Project\\\\\\\\MODEL_GEN\\\\\\\\stopwords.txt\\\" -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 2 -min 2\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Bigram - TFIDF - INCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB212.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -T -I -N 0 -L -stemmer weka.core.stemmers.SnowballStemmer -M 1 -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 2 -min 2\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Unigram - TF - EXCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB121.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -T -N 0 -L -S -stemmer weka.core.stemmers.SnowballStemmer -M 1 -stopwords \\\"E:\\\\\\\\Higher Studies\\\\\\\\STUDY\\\\\\\\Semester3\\\\\\\\NLP\\\\\\\\Project\\\\\\\\MODEL_GEN\\\\\\\\stopwords.txt\\\" -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 1 -min 1\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Unigram - TF - INCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB122.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -T -N 0 -L -stemmer weka.core.stemmers.SnowballStemmer -M 1 -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 1 -min 1\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Bigram - TF - EXCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB221.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -T -N 0 -L -S -stemmer weka.core.stemmers.SnowballStemmer -M 1 -stopwords \\\"E:\\\\\\\\Higher Studies\\\\\\\\STUDY\\\\\\\\Semester3\\\\\\\\NLP\\\\\\\\Project\\\\\\\\MODEL_GEN\\\\\\\\stopwords.txt\\\" -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 2 -min 2\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Bigram - TF - INCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB222.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -T -N 0 -L -stemmer weka.core.stemmers.SnowballStemmer -M 1 -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 2 -min 2\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Unigram - PNP - EXCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier 	-t train.arff 	-d train_NB131.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter 		-F \"weka.filters.unsupervised.attribute.StringToWordVector 	-R first-last -W 100000 -prune-rate -1.0 -N 0 -L 	-S -stemmer weka.core.stemmers.SnowballStemmer -M 1 	-stopwords \\\"E:\\\\\\\\Higher Studies\\\\\\\\STUDY\\\\\\\\Semester3\\\\\\\\NLP\\\\\\\\Project\\\\\\\\MODEL_GEN\\\\\\\\stopwords.txt\\\" 		-tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 1 -min 1\\\"\" 	-F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" 	-W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Unigram - PNP - INCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier 	-t train.arff 	-d train_NB132.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter 		-F \"weka.filters.unsupervised.attribute.StringToWordVector 	-R first-last -W 100000 -prune-rate -1.0 -N 0 -L 	-stemmer weka.core.stemmers.SnowballStemmer -M 1 	-tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 1 -min 1\\\"\" 	-F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" 	-W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Bigram - PNP - EXCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB231.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -N 0 -L -S -stemmer weka.core.stemmers.SnowballStemmer -M 1 -stopwords \\\"E:\\\\\\\\Higher Studies\\\\\\\\STUDY\\\\\\\\Semester3\\\\\\\\NLP\\\\\\\\Project\\\\\\\\MODEL_GEN\\\\\\\\stopwords.txt\\\" -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 2 -min 2\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --

echo 'Train: NB - Bigram - PNP - INCL SW'
java -classpath %classpath% weka.classifiers.meta.FilteredClassifier -t train.arff 	-d train_NB232.model 	-c 2 -x 3 -v -o 	-F "weka.filters.MultiFilter -F \"weka.filters.unsupervised.attribute.StringToWordVector -R first-last -W 100000 -prune-rate -1.0 -N 0 -L -stemmer weka.core.stemmers.SnowballStemmer -M 1 -tokenizer \\\"weka.core.tokenizers.NGramTokenizer -delimiters \\\\\\\" \\\\\\\\r\\\\\\\\n\\\\\\\\t.,;:\\\\\\\\\\\\\\\'\\\\\\\\\\\\\\\"()?!\\\\\\\" -max 2 -min 2\\\"\" -F \"weka.filters.supervised.attribute.AttributeSelection -E \\\"weka.attributeSelection.InfoGainAttributeEval \\\" -S \\\"weka.attributeSelection.Ranker -T 0.0 -N -1\\\"\"" -W weka.classifiers.bayes.NaiveBayes --
